version: 3
services:
  web:
    image: srealzhang/aiixm:part2
    deploy:
      replicas: 5
      resources: 
        limits:
          cpus: "0.1"
          memory: 50M
      restart_poolicy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
